### ISSUE TITLE
Can't find brew after initial install

### ISSUE THREAD

**Issue by tsalright** [Defilan/dotfiles#11]
When I went to run the install script, after the brew.sh, it failed to find brew because it wasn't in the path. To get around this in my install, I referenced the install path that Brew tells you to export in a .zprofile. I basically updated the line below from brew to  `/opt/homebrew/bin/brew` and it worked like a charm. You may find a more elegant solution, but this worked in the pinch I was in.

https://github.com/Defilan/dotfiles/blob/b48a4dbbb6019de22648af54b0ab39231eae8391/install.sh#L14

**Comment by Defilan** [comment]
I'm checking this out now, sorry for the delay @tsalright

**Comment by Defilan** [comment]
Finally fixed this with the latest update on 04/10/24. Should be fixed now!
